CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  user_uuid UUID NOT NULL,
  username VARCHAR NOT NULL,
  hash BYTEA NOT NULL,
  salt VARCHAR(255) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  play_count INTEGER NOT NULL DEFAULT 0,
  win_count INTEGER NOT NULL DEFAULT 0,
  experience INTEGER NOT NULL DEFAULT 0,
  score INTEGER NOT NULL DEFAULT 0,
  profile_picture INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX email_idx ON users(email);