CREATE TABLE games (
  game_id UUID NOT NULL,
  finished BOOLEAN NOT NULL,
  winner_team VARCHAR(12),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  p1_id UUID NOT NULL,
  p1_team VARCHAR(12),
  p1_score INTEGER NOT NULL,
  p2_id UUID NOT NULL,
  p2_team VARCHAR(12),
  p2_score INTEGER NOT NULL,
  p3_id UUID,
  p3_team VARCHAR(12),
  p3_score INTEGER,
  p4_id UUID,
  p4_team VARCHAR(12),
  p4_score INTEGER,
  p5_id UUID,
  p5_team VARCHAR(12),
  p5_score INTEGER,
  p6_id UUID,
  p6_team VARCHAR(12),
  p6_score INTEGER,
  p7_id UUID,
  p7_team VARCHAR(12),
  p7_score INTEGER,
  p8_id UUID NOT NULL,
  p8_team VARCHAR(12),
  p8_score INTEGER
);
