version: '3.1'

services:

  db:
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=3GB"
    environment:
      POSTGRES_PASSWORD: MOGB3
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080